AWSTemplateFormatVersion: 2010-09-09
Description: The Video application - transcoder template.

Parameters:
  CloudFormationLambdaArn:
    Type: String
    Description: Lambda that handle's Custom CloudFormation Resources

  VPCStack:
    Type: String
    Description: VPC Stack Name

  SharedStack:
    Type: String
    Description: Shared Stack name

  Environment:
    Description: Environment - prod or sandbox
    Type: String
    Default: prod

Resources:

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName:
        Fn::Join:
          - ''
          - - 'video/transcoder/'
            - Ref: Environment

Outputs:
  Repository:
    Value: !Ref 'Repository'
    Export:
      Name: !Sub '${AWS::StackName}-Repository'
  RepositoryUrl:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}"
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryUrl'