version: 0.2

# aws/codebuild/eb-nodejs-6.10.0-amazonlinux-64:4.0.0
phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd ./cloudformation/custom && npm install
  build:
    commands:
      - echo Testing the code
      - npm test
      - echo Removing dev dependencies
      - rm -Rf node_modules
      - npm install --production
  post_build:
    commands:
      - zip -r build.zip .
      - update-function-code --function-name "${CloudFormationLambda}" --zip-file build.zip --publish
artifacts:
  base-directory: 'cloudformation/custom'
  files:
    - '**/*'
  type: zip